# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x1c\n\x0cWriteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0bReadRequest\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\x10ReplicateRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"$\n\x11ReplicateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1b\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\"#\n\x0cVoteResponse\x12\x13\n\x0bvoteGranted\x18\x01 \x01(\x08\x32\xb3\x01\n\x0bRaftService\x12&\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12\x32\n\tReplicate\x12\x11.ReplicateRequest\x1a\x12.ReplicateResponse\x12#\n\x04Vote\x12\x0c.VoteRequest\x1a\r.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST']._serialized_start=14
  _globals['_WRITEREQUEST']._serialized_end=42
  _globals['_WRITERESPONSE']._serialized_start=44
  _globals['_WRITERESPONSE']._serialized_end=76
  _globals['_READREQUEST']._serialized_start=78
  _globals['_READREQUEST']._serialized_end=91
  _globals['_READRESPONSE']._serialized_start=93
  _globals['_READRESPONSE']._serialized_end=121
  _globals['_REPLICATEREQUEST']._serialized_start=123
  _globals['_REPLICATEREQUEST']._serialized_end=155
  _globals['_REPLICATERESPONSE']._serialized_start=157
  _globals['_REPLICATERESPONSE']._serialized_end=193
  _globals['_VOTEREQUEST']._serialized_start=195
  _globals['_VOTEREQUEST']._serialized_end=222
  _globals['_VOTERESPONSE']._serialized_start=224
  _globals['_VOTERESPONSE']._serialized_end=259
  _globals['_RAFTSERVICE']._serialized_start=262
  _globals['_RAFTSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
